CREATE DATABASE IF NOT EXISTS grocery;
USE grocery;

CREATE TABLE IF NOT EXISTS products (
  serial_no VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
  uid INT AUTO_INCREMENT UNIQUE,
  phone VARCHAR(32) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  credit DECIMAL(10,2) NOT NULL DEFAULT 0.00
);
